### ISSUE TITLE
[Architect] 사용자 여정 및 ToDo list

### ISSUE THREAD

**Issue by 4923** [4923/offego#1]
# User Journey

1. 페이지에 입장
2. 단순한 메인페이지 -> 기능으로 접근하는 과정
3. 프롬프트 생성용 정보 입력
    - 이름 (개인정보 이슈가 걱정된다면 가명 또는 공란 가능) → 텍스트 입력
    - 대상 및 관계 → 이걸 분리해서 받아야하는지 받아서 후처리 하는게 나을지는 입력받을 문항 목록에 따라 달라질 듯.
    - 목적 (e.g. 증원메일, 과제 문의 메일, 학내 공지) → 텍스트 입력
    - 반드시 포함할 내용 → 장문이어도 ok이나 가능하면 키워드 위주로.
    - (선택) 성격 → 안내문구: 기본적으로 목적에 맞게 문장을 생성하나 성격을 드러내고 싶다면 입력해주세요.
4. 대기화면 (api call 돌아올 때까지 loading css kit 아무거나 사용)
5. 결과화면 출력 (Result)
    - 코드블럭 copy 처럼 전문 복사하는 기능
    - 수정이 필요할 경우 내부에서 텍스트를 수정할 수 있는 기능
    - (가능?) 이 내용을 기반으로 좀 더 ___ 하게 해줘, 하고 요청할 수 있게 하는 기능 (ReGen)
6. 결과를 다시 ChatGPT 에게 보내 평가를 받는 과정, 이 때 키워드와 예상 답변까지 출력

# Todo's

- [ ] 기본 페이지 생성
    - ./src/routes
        | Page name | Functions |
        | :-------- | :-------- |
        | `Main.svelte`     | 중앙 of 중앙에 : input(f”{______} 의 공적 자아) → 로 로그인   |
        | `UserInfo.svelte` | 사용자의 설정값을 미리 받아 프롬프트를 생성하는 페이지 (키워드 위주, 성격까지 표현 가능한 것으로 앎)     |
        | `Result.svelte`   | (ChatGPT) 에게 UserInfo 에서 정리된 프롬프트를 전송 → 결과값을 받아 텍스트로 변형 (가능하면 맞춤법 검사, 키워드 추출을 활용)  |
        | `Eval.svelte`     | 평가 또한 ChatGPT에게 받을 것 (어떤 평가를 출력할 것인지 미리 세팅해야 함)    |
    - ./src/lib
        - /components
            - /layout : 기본 레이아웃 세팅
                - Nav.svelte → ChatGPT란? (사용시 주의점)
                - Header.svelte → 처음으로 돌아가기 (중앙 상단 로고), 
                - Footer.svelte → Swydy에서 제작, 제작자 연락처, 한국외대 멋쟁이사자처럼 (소속으로 참여했으니)
            - /feature : 사용자에게 보이지 않는 기능을 구현 → 3번에서 프롬프트 생성용 정보를 받아와야하는데
                - Keywords.svelte : UserInfo 에서 받아온 정보를 후처리 또는 가공해서 (맞춤법, 띄어쓰기) store에 보내는 역할
                - Prompt.svelte : UserInfo.svelte 에서 받아온 답 (키워드) 으로 text Generate
                - **Generate.svelte** : Prompt.svelte에서 받아온 내용으로 텍스트 생성 → 직접 API와 소통하는 파트, store로 결과 전송
                - **ReGenerate.svelte** : store에서 결과 받아와서 입력으로 다시 보내고 → Keywords 또는 Generate를 호출해 새 결과
        - /helpers
            - network.js
                - 아마도 `store` 에서 출력값을 관리해야 할 듯 함.
                  : username, target, relationship, purpose, essential, result

- [ ] 자잘한 디자인 설정
    - 엄청나게 거슬리는 favicon
    - css 정리
        - 폰트
        - 반응형 못해... 중앙에 텍스트만 붙일건데 백그라운드색과 텍스트 색은 바꿔야 할 것 같음 (미색정도의 차이를 주거나 흑/백으로 하거나)
    - [ ] 모바일 막고싶은데 아무래도 모바일 사용자가 더 많을 것 같아 고민.
